_wandb:
    value:
        cli_version: 0.23.1
        e:
            oi8q7otiktdo6pnr0iybndup8yj5ia8d:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                args:
                    - --batch_size
                    - "4"
                    - --compile
                    - "False"
                    - --context_length
                    - "256"
                    - --d_ff
                    - "512"
                    - --d_model
                    - "128"
                    - --data_dtype
                    - uint16
                    - --device
                    - cpu
                    - --eval_interval
                    - "5"
                    - --eval_iters
                    - "2"
                    - --max_iters
                    - "10"
                    - --num_heads
                    - "4"
                    - --num_layers
                    - "2"
                    - --optimizer
                    - adamw
                    - --train_data
                    - /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/train/TinyStoriesV2-GPT4-train_tokens_.bin
                    - --val_data
                    - /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/val/TinyStoriesV2-GPT4-valid_val_tokens_.bin
                    - --vocab_size
                    - "50257"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "219546316800"
                email: shawnspitzel@gmail.com
                executable: /Users/shawnspitzel/cs336/cs326/assignment1-basics/.venv/bin/python
                git:
                    commit: 80ef6b5f5cf4517963f3457b3dba22207843f68a
                    remote: https://github.com/shawnspitzel/cs326.git
                host: Shawns-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-13.4.1-arm64-arm-64bit
                program: -m cs336_basics.training.pretrain
                python: CPython 3.12.7
                root: /Users/shawnspitzel/cs336/cs326/assignment1-basics
                startedAt: "2026-01-02T07:07:01.427410Z"
                writerId: oi8q7otiktdo6pnr0iybndup8yj5ia8d
        m:
            - "1": iteration
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 4
beta1:
    value: 0.9
beta2:
    value: 0.999
checkpoint_dir:
    value: null
checkpoint_interval:
    value: 1000
compile:
    value: false
context_length:
    value: 256
cosine_iters:
    value: 100000
d_ff:
    value: 512
d_model:
    value: 128
data_dtype:
    value: uint16
device:
    value: cpu
eval_interval:
    value: 5
eval_iters:
    value: 2
gradient_clip_norm:
    value: 1
learning_rate:
    value: 0.0006
log_interval:
    value: 100
max_iters:
    value: 10
min_lr:
    value: 6e-05
num_heads:
    value: 4
num_layers:
    value: 2
optimizer:
    value: adamw
profile:
    value: false
profile_output:
    value: checkpoints/profile_stats.prof
resume_from:
    value: null
seed:
    value: 42
theta:
    value: 10000
train_data:
    value: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/train/TinyStoriesV2-GPT4-train_tokens_.bin
use_params:
    value: false
use_wandb:
    value: false
val_data:
    value: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/val/TinyStoriesV2-GPT4-valid_val_tokens_.bin
vocab_size:
    value: 50257
wandb_project:
    value: cs336-assignment1
wandb_run_name:
    value: null
warmup_iters:
    value: 2000
weight_decay:
    value: 0.01
